### ISSUE TITLE
How can a 2D plot be saved using tf-plot ? 

### ISSUE THREAD

**Issue by mohapatras** [wookayin/tensorflow-plot#14]
Acc to docs, tf_plot returns images in 3-D instead of 2D. I do not find any api where a 2D plot can be returned. Please suggest some ways to achieve that.

**Comment by wookayin** [comment]
Hi, plot op always returns the image as a RGBA image, hence 3D `[height, width, 4]`. Why do you need 2D plot, and how? Can you please specify your use cases (e.g. input and output)?

**Comment by wookayin** [comment]
Closing this as considered invalid. Please re-open if you need more help.
