### ISSUE TITLE
summary_image_v1 = tf.compat.v1.summary.image AttributeError: 'module' object has no attribute 'v1'

### ISSUE THREAD

**Issue by bjtuln** [wookayin/tensorflow-plot#19]

**Comment by SPDQ** [comment]
I met the same problem

**Comment by wookayin** [comment]
Which tensorflow versions are you using? I guess it would be TF 1.14 or 2.0-nightly?

**Comment by wookayin** [comment]
Reproduced at TF=1.12. It was requiring TF 1.13+ (due to changes of #15 but I will relax the minimum version requirement.
