### ISSUE TITLE
Weird colors in tfplot images

### ISSUE THREAD

**Issue by medhapotluri** [wookayin/tensorflow-plot#2]
<img width="350" alt="screen shot 2017-08-08 at 11 21 19 am" src="https://user-images.githubusercontent.com/14242853/29079773-0f54c34c-7c2c-11e7-8a72-1a33b6aa1fc0.png">
<img width="350" alt="screen shot 2017-08-08 at 11 22 24 am" src="https://user-images.githubusercontent.com/14242853/29079752-ffd13f54-7c2b-11e7-9b93-a36e5c23eb3a.png">
<img width="349" alt="screen shot 2017-08-08 at 11 21 48 am" src="https://user-images.githubusercontent.com/14242853/29079762-090ef944-7c2c-11e7-88cc-7350aadfd684.png">
<img width="348" alt="screen shot 2017-08-08 at 11 22 33 am" src="https://user-images.githubusercontent.com/14242853/29079739-f6f2620a-7c2b-11e7-98e5-3e9575c92464.png">

The first two images are the original images, and the next two are the results of the following chunk of code. I'm not sure if this is a tfplot issue or something else, but I was wondering if you had any idea what could be causing the images to look like this. Thanks!

   ```
def plot_func(cx, cy, projected_points, image):
      fig = matplotlib.figure.Figure()
      ax = fig.add_subplot(111)
      ax.plot([cx, cx + projected_points[0][0]], [cy, cy + projected_points[0][1]], 'b', linewidth=3, zorder=1)
      ax.plot([cx, cx + projected_points[1][0]], [cy, cy + projected_points[1][1]], 'r', linewidth=3, zorder=1)
      ax.plot([cx, cx + projected_points[2][0]], [cy, cy + projected_points[2][1]], 'g', linewidth=3, zorder=1)
      ax.imshow(image)
      return fig

    img = tfplot.plot(plot_func, [cx, cy, projected_points, image])
    return tf.expand_dims(img, 0)
      
detected_poses = draw_pose(tf.squeeze(original_image, axis=0), detection_poses[top_index[0]], normalized_boxes[top_index[0]], tf.to_float(original_image_shape))
tf.summary.image('detected_poses', detected_poses)
```

**Comment by wookayin** [comment]
Please validate and sanitize dtype and range of img. For example, if its dtype is float32 but ranges [0, 255] instead of [0, 1], the problem might happen.

BTW I think it could be better to emit warning messages in such cases.
