### ISSUE TITLE
Introduce decorator-style API

### ISSUE THREAD

**Issue by wookayin** [wookayin/tensorflow-plot#3]
Decorators are pretty?

For example (name is undecided), we can simply define a decorated "op builder" function:

```python
@tfplot.op(batch=True)
def plot_heatmap(heatmap, cmap='jet')
    # heatmap: a [16x16] numpy array here
    fig, ax = tfplot.subplots(figsize=(4, 3))
    im = ax.imshow(heatmap, cmap=cmap)
    fig.colorbar(im)
    return fig

# heatmap_tensor : a float32 Tensor of shape [4, 16, 16], for example
>>> plot_heatmap(heatmap_tensor)
Tensor("PlotHeatmap:0", shape=(4, ?, ?, 3), dtype=uint8)
```

Instead of:

```python
# heatmap_tensor : a float32 Tensor of shape [4, 16, 16], for example
>>> PlotOp = tfplot.wrap(figure_heatmap, batch=True, name='PlotHeatmap')
>>> PlotOp(heatmap_tensor)
Tensor("PlotHeatmap:0", shape=(4, ?, ?, 3), dtype=uint8)
```

**Comment by ferrine** [comment]
Decorator is a cool thing, should have batch/name arguments. As I understand the implementation, the following should work as well. I think it will be a good thing to work around with first argument of `wrap` function and in case it is not defined, create a factory wrapper function that decorates `plot_heatmap` in above example

```python
import functools
NotDefined = object()
def wrap(func=NotDefined, arg=1, **kwargs):
    if func is NotDefined:
        args = locals().copy()
        args.pop('func')
        args.pop('kwargs')
        args.update(kwargs)
        return functools.partial(wrap, **args)
    # or your code below
    def wrapped(**kwargs1):
        if arg == 1:
            print('hi')
        else:
            print('bye')
        kw = kwargs.copy()
        kw.update(kwargs1)
        return func(**kw)
    return wrapped

def fn1(a=1, b=2):
    print('a =', a)
    print('b =', b)
@wrap
def fn2(a=1, b=2):
    print('a =', a)
    print('b =', b)

@wrap(arg=2)
def fn3(a=1, b=2):
    print('a =', a)
    print('b =', b)

fn4 = wrap(fn1, arg=2, a=3)

fn1()
fn2()
fn3()
fn4()
-------------
a = 1
b = 2
hi
a = 1
b = 2
bye
a = 1
b = 2
bye
a = 3
b = 2
```

**Comment by ferrine** [comment]
you can use https://github.com/ferrine/biwrap, available at pypi

**Comment by wookayin** [comment]
Nice suggestion! I will take a look at this soon.

**Comment by wookayin** [comment]
I have been working on this these days, please see #7 (in progress).

* `tfplot.wrap`: The existing `tfplot.wrap()` can be used as a decorator as well, as suggested by @ferrine.
* `tfplot.autowrap`: Similar to `wrap`, but supports automatic injection of `fig`, `ax`. This will replace `wrap_axesplot` soon. Batch supports, etc. will be added soon.

/cc @ferrine Do you want to take a look or review it?

**Comment by wookayin** [comment]
I believe this API is good enough, will be released as v0.3.

https://github.com/wookayin/tensorflow-plot/blob/master/examples/showcases.ipynb

**Comment by ferrine** [comment]
Oh, I was missiing notifications for a long time, is review still needed?

**Comment by wookayin** [comment]
If you want to kindly give some suggestions, it would be greatly appreciated of course.
